syntax on

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch

set colorcolumn=80
highlight ColorColumn ctermbg=darkgrey guibg=darkgrey

call plug#begin('~/.vim/plugged')

Plug 'editorconfig/editorconfig-vim'

" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
" Plug 'junegunn/fzf.vim'
" Plug 'tweekmonster/gofmt.vim'
" Plug 'tpope/vim-fugitive'
" Plug 'vim-utils/vim-man'
" Plug 'mbbill/undotree'
" Plug 'sheerun/vim-polyglot'
" Plug 'vuciv/vim-bujo'
" Plug 'tpope/vim-dispatch'
" Plug 'theprimeagen/vim-apm'
" Plug 'theprimeagen/vim-be-good', {'do': './install.sh'}

" x
" "  I AM SO SORRY FOR DOING COLOR SCHEMES IN MY VIMRC

" Plug 'sainnhe/gruvbox-material'
" Plug 'colepeters/spacemacs-theme.vim'
" Plug 'phanviet/vim-monokai-pro'
" Plug 'vim-airline/vim-airline'
" Plug 'flazz/vim-colorschemes'

call plug#end()
